# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - velasco-llano-actividad6

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_5d47b72a94684dc4b124a09da5ca54df }}
        password: ${{ secrets.AzureAppService_ContainerPassword_62b80b8a90dd45fcaa0411c9de5d11f3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5d47b72a94684dc4b124a09da5ca54df }}/velasco_llano_act6:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'velasco-llano-actividad6'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9b3dfe673c3c4ae5877f8230b28dc26f }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5d47b72a94684dc4b124a09da5ca54df }}/velasco_llano_act6:${{ github.sha }}'